// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PickPoints.Infrastructure.Data;

namespace PickPoints.Infrastructure.Migrations
{
    [DbContext(typeof(PickPointsDbContext))]
    partial class PickPointsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("PickPoints.Core.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<string[]>("Goods")
                        .HasColumnType("text[]");

                    b.Property<int?>("PostampId")
                        .HasColumnType("integer");

                    b.Property<string>("RecipientFullname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecipientPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PostampId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PickPoints.Core.Entities.Postamp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Postamps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Авиаторов, улица 30",
                            IsActive = true,
                            Number = "1111-111"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Авиаторов, улица 30",
                            IsActive = true,
                            Number = "2222-222"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Авиаторов, улица 30",
                            IsActive = false,
                            Number = "3333-333"
                        });
                });

            modelBuilder.Entity("PickPoints.Core.Entities.Order", b =>
                {
                    b.HasOne("PickPoints.Core.Entities.Postamp", "Postamp")
                        .WithMany()
                        .HasForeignKey("PostampId");

                    b.Navigation("Postamp");
                });
#pragma warning restore 612, 618
        }
    }
}
